#!/bin/bash -e

eval "$(cli-shezargs $@)"

[[ -n $project          ]] || die "gpcf: Need --project="
[[ -n $domain_name      ]] || die "gpcf: Need --domain-name="
[[ -n $test_domain_name ]] || die "gpcf: Need --test-domain-name="

[[ -z $pid ]] && export pid="$$"

for stack in cluster test; do
  for color in blue green teal yellow; do

    serverassist-crypto gen-fqdn-cert --project="$project" --fqdn="$color-$stack.$test_domain_name" --domain-name="$domain_name"

  done
done

for stack in pub; do
  for color in blue green teal yellow; do

    serverassist-crypto gen-fqdn-cert --project="$project" --fqdn="$color-$stack.$domain_name" --domain-name="$domain_name"

  done
done

