#!/bin/bash -e

eval "$(cli-shezargs $@)"

[[ -n $project          ]] || die "Need --project="
[[ -n $domain_name      ]] || die "Need --domain-name="
[[ -n $test_domain_name ]] || die "Need --test-domain-name="

for stack in cluster test; do
  for color in blue green teal yellow; do

    serverassist-crypto gen-fqdn-cert --project="$project" --fqdn="$color-$stack.$test_domain_name"

  done
done

for stack in pub; do
  for color in blue green teal yellow; do

    serverassist-crypto gen-fqdn-cert --project="$project" --fqdn="$color-$stack.$domain_name"

  done
done

