#!/bin/bash -e

removefile() {
  if [[ $1 =~ ^\.\/crypto ]]; then
    echo "rm $1"
    rm $1
  fi
}

removedir() {
  if [[ $1 =~ ^\.\/crypto-working ]]; then
    echo "rmdir $1"
    rmdir $1
  fi
}

cd /home/scotty/stmp

find . -type f | while read file; do
  if [ `stat --format=%Y $file` -le $(( `date +%s` - (3*60) )) ]; then
    removefile "$file"
  else
    echo "$file is not old enouth"
  fi
done

# Now do dirs
find . -type d | while read dir; do
  if [[ $dir != . && $dir != .. ]]; then
    if [ `stat --format=%Y $dir` -le $(( `date +%s` - (3*60) )) ]; then
      removedir "$dir"
    else
      echo "$dir is not old enouth"
    fi
  fi
done

