#!/bin/bash -e

if [[ $1 == --keys ]];then
  aws s3 ls --summarize --recursive --human-readable "s3://sa-system-storage/serverassist/secrets/" | egrep -- '-key\.json$'
  exit $?
fi

aws s3 ls --summarize --recursive --human-readable "s3://sa-system-storage/serverassist/secrets/" | egrep -v -- '-key\.json$'

