#!/bin/bash -e

if [[ $1 == --keys ]];then
  aws s3 ls --summarize --recursive --human-readable "s3://sa-system-storage/" | egrep '/secrets/' | egrep -- '-key\.json$'
  exit $?
fi

aws s3 ls --summarize --recursive --human-readable "s3://sa-system-storage/" | egrep '/secrets/' | egrep -v -- '-key\.json$'

