#!/bin/bash -e

# mount-react ~/dev/mario-sys-viewer --project=sa

port="7990"

eval "$(cli-shezargs $@)"

# ---------- Process the args ----------

repo="$1"

[[ -d $repo     ]] || die "Usage: mount-react project-dir"

if [[ -z $app ]]; then
  cd $repo
  app="$(basename `cat package.json | jq -r .homepage`)"
fi

[[ -z $app      ]] && die "Need --app="

if [[ -z $project ]]; then
  cd $repo
  [[ $(cat package.json | jq -r .homepage) =~ mobilewebassist ]] && project="sa"
fi

[[ -z $project  ]] && die "Need --project="

# ---------- Done processing the args ----------


# ---------- Run a development server? ----------
if [[ -n $dev ]]; then

  # NOTE: does not really work right.

  cd $scripts_dir/..
  ra invoke ra-scripts/mount-react.js mount --port="$port" --name="${project}_console_${app}"

  cd $repo
  [[ -d node_modules ]] || yarn install
  yarn start

  kill %1
fi

# ---------- Run a Node-based static file server `serve` ----------
echo "Launching $repo (as $project $app) with serve --port=$port"

cd $repo
[[ -d node_modules ]] || yarn install
yarn run build
cd build && pm2 start serve --name "${app}-serve" -- --port="$port"

cd $scripts_dir/..
pm2 start lib/mount-react.js --name "${app}-mount" -- --port="$port" --name="${project}_console_${app}"

