#!/bin/bash -e

eval "$(cli-shezargs $@)"

[[ -z $project  ]] && project="serverassist"
[[ -z $area     ]] && area="deploy"

# Make sure we have a secure place to work
mkdir -p ~/stmp && cd $_
chmod og-rwx ~/stmp

orig_file="$1"
secret_file="$(basename $1)"

cd ~/stmp/
aws s3 cp "s3://sa-system-storage/${project}/secrets/${area}/${orig_file}.enc" ./

# Get key, if we do not already have it
if ! [[ -f ${project}-data-key.json ]]; then
  aws s3 cp "s3://sa-system-storage/${project}/secrets/deploy/${project}-data-key.json" ./
  created_data_key="1"
fi

# Get the plain-text version of the data-key
cat ${project}-data-key.json | underscore 'select' '.CiphertextBlob' --outfmt=text | base64 -d > binary-blob
key="$(aws kms decrypt --ciphertext-blob fileb://binary-blob | underscore 'select' '.Plaintext' --outfmt=text)"
rm binary-blob

# Decrypt
openssl enc -aes-256-cbc -d -a -in "${secret_file}.enc" -out "${secret_file}" -k "$key"

[[ -n ${created_data_key} ]] && rm ~/stmp/${project}-data-key.json
[[ -f ${secret_file}.enc  ]] && rm ${secret_file}.enc

