#!/bin/bash -e

eval "$(cli-shezargs $@)"

test -f $1 || die "Usage: $0 <filename>"
orig_file="$1"
secret_file="$(basename $1)"

[[ -z $project  ]] && project="serverassist"
[[ -z $area     ]] && area="deploy"

# Make sure we have a secure place to work
mkdir -p ~/stmp
chmod og-rwx ~/stmp

shift
[[ $# > 0 ]] && storage_dir="$1"

[[ -n $storage_dir ]] && echo "using ${storage_dir} to store"

if [[ $(dirname $(readlink -f $orig_file)) != $HOME/stmp ]]; then
  cp ${orig_file} ~/stmp/
fi

cd ~/stmp/

# Get key, if we do not already have it
if ! [[ -f ${project}-data-key.json ]]; then
  aws s3 cp "s3://sa-system-storage/${project}/secrets/deploy/${project}-data-key.json" ./
  created_data_key="1"
fi

# Get the plain-text version of the data-key
cat ${project}-data-key.json | underscore 'select' '.CiphertextBlob' --outfmt=text | base64 -d > binary-blob
key="$(aws kms decrypt --ciphertext-blob fileb://binary-blob | underscore 'select' '.Plaintext' --outfmt=text)"
rm binary-blob

#encrypt
openssl enc -aes-256-cbc -a -salt -in "${secret_file}"  -out "${secret_file}.enc" -k "$key"

# Copy to store
destination="s3://sa-system-storage/${project}/secrets/${area}/"
[[ -n $storage_dir ]] && destination="${destination}${storage_dir}"
aws s3 cp ${secret_file}.enc "$destination"

[[ -n ${created_data_key} ]] && rm ~/stmp/${project}-data-key.json
[[ -f ${secret_file}      ]] && rm $secret_file
[[ -f ${secret_file}.enc  ]] && rm ${secret_file}.enc


