#!/bin/bash -e

username="$USER"
client_cert="$HOME/.ssh/keys/serverassist/client-certs/${username}_mobilewebassist_client.pem"
if ! [[ -f $client_cert ]]; then
  client_cert="/tmp/certs/userx_mobilewebassist_client.pem"
fi

server_cert="$HOME/.ssh/keys/serverassist/mobilewebassist_root_server_ca.crt"
if ! [[ -f $server_cert ]]; then
  server_cert="/tmp/certs/mobilewebassist_root_server_ca.crt"
fi

stat $client_cert
stat $server_cert

curl --cert "$client_cert" --cacert "$server_cert" $@

