#!/bin/bash -e

client_cert="$HOME/.ssh/keys/serverassist/client-certs/${USER}_mobilewebassist_client.pem"
if ! [[ -f $client_cert ]]; then
  client_cert="/tmp/certs/userx_mobilewebassist_client.pem"
fi

server_cert="$HOME/.ssh/keys/serverassist/mobilewebassist_root_server_ca.crt"
if ! [[ -f $server_cert ]]; then
  server_cert="/tmp/certs/mobilewebassist_root_server_ca.crt"
fi

curl --cert "$client_cert" --cacert "$server_cert" "$@"
exit $?


# This is how you use openssl like telnet to the fqdn
export client_cert="$HOME/.ssh/keys/serverassist/client-certs/${USER}_mobilewebassist_client.pem"
export server_cert="$HOME/.ssh/keys/serverassist/mobilewebassist_root_server_ca.crt"

openssl s_client -CAfile "${server_cert}" -cert "${client_cert}" -connect fqdn:443

