#!/bin/bash -e

orig_args="$@"

eval "$(cli-shezargs $@)"

if [[ -n $json ]]; then
  ra invoke $scripts_dir/../ra-scripts/routing.js setRouting $orig_args | underscore print --color
else
  ra invoke $scripts_dir/../ra-scripts/routing.js setRouting $orig_args
fi

