#!/bin/bash -e

orig_args="$@"

eval "$(cli-shezargs $@)"

if ra invoke $scripts_dir/../ra-scripts/routing.js setRouting $orig_args > /tmp/set-routing-$$.json; then
  cat /tmp/set-routing-$$.json | underscore print --color
fi

