#!/bin/bash -e

orig_args="$@"

eval "$(cli-shezargs $@)"

if ra invoke $scripts_dir/../ra-scripts/routing.js showRouting $orig_args > /tmp/show-routing-$$.json; then
  cat /tmp/show-routing-$$.json | underscore print --color
fi

